// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/workspace/AoneUI/node_modules/.pnpm/registry.npmmirror.com+dumi@2.2.1_@babel+core@7.22.5_eslint@8.35.0_postcss@8.4.21_prettier@2._yeqgwzjaoy5z7gduepczkg6zxy/node_modules/dumi/theme-default/slots/Sidebar/index.js';
