// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/getting-started.zh-CN":{"path":"getting-started","id":"docs/getting-started.zh-CN","parentId":"DocLayout"},"docs/getting-started":{"path":"getting-started","id":"docs/getting-started","parentId":"DocLayout"},"docs/index.zh-CN":{"path":"","id":"docs/index.zh-CN","parentId":"DocLayout"},"docs/help.zh-CN":{"path":"help","id":"docs/help.zh-CN","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"docs/help":{"path":"help","id":"docs/help","parentId":"DocLayout"},"components/button/index":{"id":"components/button/index","path":"components/button","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "dumi__pages__404" */'@/dumi__pages/404')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__ContextWrapper" */'@/dumi__theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__layouts__DocLayout" */'@/dumi__theme/layouts/DocLayout')),
'docs/getting-started.zh-CN': React.lazy(() => import(/* webpackChunkName: "docs__getting-started.zh-CN.md" */'H:/AoneUI/docs/getting-started.zh-CN.md')),
'docs/getting-started': React.lazy(() => import(/* webpackChunkName: "docs__getting-started.md" */'H:/AoneUI/docs/getting-started.md')),
'docs/index.zh-CN': React.lazy(() => import(/* webpackChunkName: "docs__index.zh-CN.md" */'H:/AoneUI/docs/index.zh-CN.md')),
'docs/help.zh-CN': React.lazy(() => import(/* webpackChunkName: "docs__help.zh-CN.md" */'H:/AoneUI/docs/help.zh-CN.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'H:/AoneUI/docs/index.md')),
'docs/help': React.lazy(() => import(/* webpackChunkName: "docs__help.md" */'H:/AoneUI/docs/help.md')),
'components/button/index': React.lazy(() => import(/* webpackChunkName: "button__index.md" */'H:/AoneUI/src/button/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "dumi__pages__Demo" */'@/dumi__pages/Demo')),
},
  };
}
