// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'H:/AoneUI/node_modules/.pnpm/registry.npmmirror.com+dumi@2.2.1_gje3yeff4mavut43kfm2fcqwky/node_modules/dumi/theme-default/slots/SearchResult/index.js';
